### ISSUE TITLE
Unclear how to import packages for Typescript/Javascript

### ISSUE THREAD

**Issue by MarcCoquand** [twibiral/obsidian-execute-code#217]
Hi! I absolutely love this tool. Thank you so much for developing it.

I can't really figure out how we are supposed to import packages in typescript. It says that we can use the `{pre}` script to add our dependencies. I assume there we add all `import x`, however the runtime will complain that it can't find that package. I can not figure out what is best practice for installing the package itself.

Thank you so much again for support and for developing this tool.

**Comment by chlohal** [comment]
When you're importing, TS/JS expect you to have a `node_modules` directory. The plugin creates a new file for each code block, so iirc that's why it can't find them.

You could try installing the dependencies globally with `npm i -g <package>`; I think that will help?

Sorry :)

**Comment by MarcCoquand** [comment]
I tried adding it globally, but it didn't seem to work.

```
const _ = require('lodash')

Error: Cannot find module 'lodash'
Require stack:
- <repl>
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at eval (eval at <anonymous> (REPL6:1:7), <anonymous>:4:11)
    at REPL6:1:7
    at Script.runInContext (vm.js:144:12)
    at REPLServer.defaultEval (repl.js:568:29)
    at bound (domain.js:421:15)
    at REPLServer.runBound [as eval] (domain.js:432:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '<repl>' ]
```

after successfully running `npm i -g lodash`

**Comment by MarcCoquand** [comment]
I can confirm also that it works when I try it in a regular node REPL in a terminal.

```
which node
/Users/me/.nvm/versions/node/v14.20.0/bin/node
```

which is the same as node path I've set in my Obsidian code execute config 🤔 
```
/Users/me/.nvm/versions/node/v14.20.0/bin/node
```

**Comment by JustinS1209** [comment]
Hey! I am running into the same issue. Maybe it has something to do with nvm? I am also using nvm and Obsidian Code Blocks don't find any packages that were installed.

**Comment by twibiral** [comment]
Hi everyone,

I have the suspicion that this problem is connected to the fact that we currently do not allow access to the path variable. We are planning to add path, maybe this will fix it.

**Comment by twibiral** [comment]
@MarcCoquand and @JustinS1209 can you try to update the plugin and then try it again? With release [1.7.1](https://github.com/twibiral/obsidian-execute-code/releases/tag/1.7.1) the JS notebook mode can access the environment variables. This may fix it. Tell me how it worked, please.

**Comment by hvitis** [comment]
@twibiral 

I have similar issues but with Python. Should I open a new issue or you are working on paths within this one?

e.g. when my python code has importing it fails:
```python
No module named 'gi'
```

**Comment by mayurankv** [comment]
Python imports work completely fine for me. Are you still having issues with them?

If the javascript/typescript import issue is resolved as well, then this issue could be closed.

**Comment by pereirfe** [comment]
> Are you still having issues with them?

Just checked and still have issues

**Comment by vandernorth** [comment]
I've found a workaround:

 - I executed the following snippet from within Obsidian:
```typescript
console.log(process.argv);
```
 - This told me that the file being executed was `C:\Users\username\AppData\Local\Temp\temp_1741939057555.ts`
 - Use a terminal to go to that path: `cd C:\Users\username\AppData\Local\Temp\`
 - Installed the package there: `npm install package-name`
 - I could now use the package I wanted.

**Comment by Xananax** [comment]
I'm using Deno, and imports are statically resolved. As a result, I can't really import any file.

`@note_path` is neat, but because Deno (and modern Node) use static resolution, I can't dynamically infer the dirname from that. I'd need `@note_directory` or similar.

I have a workaround though! You _can_ import dependencies dynamically in Deno and similar, but it is a little tricky.

Then, say I created a file `test.ts` in the current Obsidian directory containing this:

```ts
export const test = () => console.log("it works")
```

And I want to import it in my Obsidian doc.

Add this to the "inject Typescript code" block in the plugin's settings:

```ts
const __dirname = [@vault_path, ... @note_path.split("/").slice(0, -1)].join("/") + "/";
Deno.chdir(__dirname);
const loadLocal = async (name: string) => await import(__dirname + name + '.ts');
```

- `__dirname` becomes a variable you can use in your blocks (I used `__dirname` to ape the Node API; feel free to use a different variable name if you use Node)
- `chdir()` sets the current working directory to the note's directory (instead of the default temp directory). This allows to write or read files from the current context. In Node, you must use `process.chdir()`.
- `loadLocal()` is a proxy to be able to load files quickly and easily. It uses the dynamic `import()` syntax, but if you use an old Node version, you could use `require()` instead.

then, the obsidian doc can have this block:

```ts
const { test } = await loadLocal('test')

test()
```

Run it, and it'll output "it works".

This also works for writing/reading files. For example, if my `test.ts` looks like this:
```ts
export const test = async () => {
  const encoder = new TextEncoder();
  const data = encoder.encode("## Hello world\n\n This is a test.");
  await Deno.writeFile("hello.md", data);
  console.log("it wrote the file")
}
```

And my note has this code block:

```ts
const { test } = await loadLocal('test')
await test()
```

(same as before, I just added `await` before `test()`)

Then a new file will be created in my vault, called `hello.md`.
